import type { SearchAutoTopKSignal, SearchScoreReason, SemanticSearchResult } from '../types';

/** Runtime calibration data. Query fixtures and benchmark mappings stay in evaluation/. */
export const SEARCH_CALIBRATION_VERSION = '2026-08-04.generic.v1';

export interface SearchCalibrationProfile {
    version: string;
    provider: string;
    model: string;
    signal: SearchAutoTopKSignal;
    intent: string;
    threshold: number;
    coefficients: {
        score: number;
        rank: number;
        margin: number;
        span: number;
        lexicalEvidence: number;
        roleMatch: number;
        duplicatePenalty: number;
        supportEvidence: number;
    };
}

export interface CalibrationFeatures {
    normalizedScore: number;
    rank: number;
    margin: number;
    span: number;
    lexicalEvidence: number;
    roleMatch: number;
    duplicatePenalty: number;
    supportEvidence: number;
}

export interface CalibratedCandidate {
    probability: number;
    features: CalibrationFeatures;
    profile: SearchCalibrationProfile;
    profileFallback: boolean;
}

const GENERIC_COEFFICIENTS = {
    score: 3.4,
    rank: 0.8,
    margin: 1.1,
    span: 0.55,
    lexicalEvidence: 2.2,
    roleMatch: 0.35,
    duplicatePenalty: -1.4,
    supportEvidence: 0.4,
} as const;

const GENERIC_THRESHOLDS: Record<SearchAutoTopKSignal, number> = {
    rerank: 0.68,
    vector: 0.76,
    hybrid_rrf: 0.74,
    mixed: 0.7,
    none: 1,
};

export function getSearchCalibrationProfile(input: {
    provider?: string;
    model?: string;
    signal: SearchAutoTopKSignal;
    intent?: string;
    profile?: SearchCalibrationProfile;
}): { profile: SearchCalibrationProfile; fallback: boolean } {
    if (input.profile) {
        return { profile: input.profile, fallback: false };
    }

    // Profiles generated by evaluation can be injected later without changing the
    // selector API. The generic profile is deliberately conservative for unknown
    // providers/models and contains no query-specific data.
    return {
        profile: {
            version: SEARCH_CALIBRATION_VERSION,
            provider: input.provider || 'generic',
            model: input.model || 'generic',
            signal: input.signal,
            intent: input.intent || 'generic',
            threshold: GENERIC_THRESHOLDS[input.signal],
            coefficients: { ...GENERIC_COEFFICIENTS },
        },
        fallback: true,
    };
}

export function calibrateSearchCandidate(
    result: SemanticSearchResult,
    index: number,
    results: readonly SemanticSearchResult[],
    signal: SearchAutoTopKSignal,
    options: {
        provider?: string;
        model?: string;
        intent?: string;
        profile?: SearchCalibrationProfile;
    } = {},
): CalibratedCandidate {
    const { profile, fallback } = getSearchCalibrationProfile({ ...options, signal });
    const scores = results
        .map(candidate => getSignalScore(candidate, signal))
        .filter((score): score is number => Number.isFinite(score));
    const score = getSignalScore(result, signal);
    const normalizedScore = normalizeScore(result, score, scores, signal);
    const previousScore = index > 0 ? getSignalScore(results[index - 1], signal) : undefined;
    const nextScore = index + 1 < results.length ? getSignalScore(results[index + 1], signal) : undefined;
    const margin = Number.isFinite(score) && Number.isFinite(nextScore)
        ? Math.max(0, (score as number) - (nextScore as number))
        : 0;
    const span = scores.length > 1
        ? Math.max(...scores) - Math.min(...scores)
        : 0;
    const features: CalibrationFeatures = {
        normalizedScore,
        rank: results.length <= 1 ? 1 : 1 - index / (results.length - 1),
        margin: normalizeMargin(margin, scores),
        span: normalizeSpan(span, scores, signal),
        lexicalEvidence: getLexicalEvidence(result),
        roleMatch: result.isPrimary === true ? 1 : 0,
        duplicatePenalty: index > 0 && result.relativePath === results[index - 1].relativePath ? 1 : 0,
        supportEvidence: Number.isFinite(previousScore) && Number.isFinite(score)
            ? Math.max(0, (previousScore as number) - (score as number))
            : 0,
    };

    const linear = profile.coefficients.score * features.normalizedScore
        + profile.coefficients.rank * features.rank
        + profile.coefficients.margin * features.margin
        + profile.coefficients.span * features.span
        + profile.coefficients.lexicalEvidence * features.lexicalEvidence
        + profile.coefficients.roleMatch * features.roleMatch
        + profile.coefficients.duplicatePenalty * features.duplicatePenalty
        + profile.coefficients.supportEvidence * features.supportEvidence
        - 2.5;

    return {
        probability: clamp01(sigmoid(linear)),
        features,
        profile,
        profileFallback: fallback,
    };
}

export function hasStrongLexicalEvidence(result: SemanticSearchResult): boolean {
    const reasons = result.scoreReasons ?? (result.scoreReason ? [result.scoreReason] : []);
    return reasons.some(reason => (
        reason === 'exact_filename'
        || reason === 'exact_symbol_definition'
        || reason === 'path_match'
    ));
}

function getSignalScore(result: SemanticSearchResult, signal: SearchAutoTopKSignal): number | undefined {
    if (signal === 'rerank') {
        return finite(result.rerankScore);
    }
    if (signal === 'mixed') {
        return finite(result.rerankScore) ?? finite(result.retrievalScore);
    }
    return finite(result.retrievalScore);
}

function getLexicalEvidence(result: SemanticSearchResult): number {
    const reasons = result.scoreReasons ?? (result.scoreReason ? [result.scoreReason] : []);
    if (reasons.includes('exact_filename') || reasons.includes('exact_symbol_definition')) {
        return 1;
    }
    if (reasons.includes('path_match') || reasons.includes('reference_match')) {
        return 0.65;
    }
    return 0;
}

function normalizeScore(
    result: SemanticSearchResult,
    score: number | undefined,
    _scores: readonly number[],
    signal: SearchAutoTopKSignal,
): number {
    if (!Number.isFinite(score) || _scores.length === 0) {
        return 0;
    }

    const value = score as number;
    // Candidate-local min/max normalization turns an arbitrary top result into
    // a certainty. Keep the score's calibrated absolute scale instead, so a
    // negative query with a uniformly weak candidate set can be rejected.
    if (signal === 'rerank') {
        return normalizeProbabilityLikeScore(value);
    }
    if (signal === 'hybrid_rrf') {
        // Reciprocal-rank fusion scores are normally below 0.02. A result
        // needs support from both channels, not merely to be first in a list.
        return clamp01(value * 45);
    }
    if (signal === 'mixed') {
        // Reranked candidates carry probability-like scores; candidates past
        // the rerank limit retain their RRF retrieval score. The source is a
        // property of the candidate, not a score magnitude.
        return finite(result.rerankScore) !== undefined
            ? normalizeProbabilityLikeScore(value)
            : clamp01(value * 45);
    }
    return normalizeProbabilityLikeScore(value);
}

function normalizeProbabilityLikeScore(value: number): number {
    return value >= 0 && value <= 1 ? clamp01(value) : clamp01(sigmoid(value));
}

function normalizeMargin(margin: number, scores: readonly number[]): number {
    if (!Number.isFinite(margin) || scores.length === 0) {
        return 0;
    }
    const span = Math.max(...scores) - Math.min(...scores);
    return span > Number.EPSILON ? clamp01(margin / span) : 0;
}

function normalizeSpan(span: number, scores: readonly number[], signal: SearchAutoTopKSignal): number {
    if (!Number.isFinite(span) || scores.length === 0) {
        return 0;
    }
    if (signal === 'rerank' || signal === 'mixed') {
        return clamp01(span / Math.max(Math.abs(Math.max(...scores)), 1));
    }
    return clamp01(span);
}

function finite(value: unknown): number | undefined {
    return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function sigmoid(value: number): number {
    if (value >= 0) {
        const z = Math.exp(-value);
        return 1 / (1 + z);
    }
    const z = Math.exp(value);
    return z / (1 + z);
}

function clamp01(value: number): number {
    return Math.max(0, Math.min(1, value));
}
